---
title: "Assignment4"
author: "Trae Smith"
date: "2024-04-07"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(lpSolve)
library(dplyr)
library(ggplot2)

##Question 1

# part A
# "The objective function is the minimum amount of cost 
# (that is, minimize z=25a+40b+30c+50d+60e)"

#part B
#"The constraints are the following:
#a+b+3c+6d+4e<=40
#0a+b+2c+10d+12e>=80
#3a+4b+12c+6d+3e>=60
#10a+12b+15c+25d+20e<=200
#15a+20b+40c+60d+50e<=700
#a,b,c,d,e>=0"

#part c

obj <- c(25,40,30,50,60)
mat <- matrix(c(1,1,3,6,4,
                0,1,2,10,12,
                3,4,12,6,3,
                10,12,15,25,20,
                15,20,40,60,50)
                ,nrow=5,byrow=TRUE)

rhs <- c(40, 80, 60, 200, 700)
dir <- c("<=", ">=", ">=", "<=", "<=")
lp_solution <- lp("min", obj, mat, dir, rhs)
print(lp_solution$solution)
print(lp_solution$objval)



##Question 2
#part a
#The response variable is the response rate, the factor is the color paper, and 
# the treatments are green, blue, and orange

#part b
#the experimental unit are the supermarket partaking lots

#part c
#Ho: u1=u2=u3, Ha:at least 1 is different 

Color <- c("Blue","Blue","Blue","Blue","Blue","Green","Green","Green","Green",
           "Green","Orange","Orange","Orange","Orange","Orange")
Rate <- c(27, 25, 30, 26, 34, 34, 29, 25, 31, 29,28, 22, 24, 26, 25)
data_input <- data.frame(Color=factor(Color), Rate)
model<-aov(Rate~Color, data=data_input)
summary(model)

#Since 0.0917<0.1, we can reject Ho and say that at least 1 ui is different 
#(where i=1,2,3)

#part d
TukeyHSD(model, "Color", conf.level = 0.90 )

#While there is no clear winner, we know that green has a higher rate than 
#orange

#Question 3
#part a

# the response variable is score on safety, block factors are the travelers, 
#and treatment factors are the 

#part b (and c, since they're the same)
Score<-c(40, 60, 60, 20, 30, 50, 50, 40, 40, 70, 60, 50, 50, 80, 60, 60)
Resort<-c("Xcaret", "Xcaret", "Xcaret", "Xcaret", "Moon Palace","Moon Palace", 
          "Moon Palace", "Moon Palace", "Garza Plaza","Garza Plaza",
          "Garza Plaza","Garza Plaza","Riu","Riu","Riu","Riu")

Traveler<-c("1","2","3","4","1","2","3","4","1","2","3","4","1","2","3","4")
data_input2<-data.frame(Resort=factor(Resort), Traveler=factor(Traveler), Score)
model2T<-aov(Score~Resort, data=data_input2) #For Treatments (that is, Resort)
model2B<-aov(Score~Traveler, data=data_input2)
summary(model2T)
summary(model2B)

#part d
#Ho: u1=u2=u3=u4, Ha: at least 1 u is different
summary(model2T)
#Since 0.211>0.05, we fail to reject Ho, which means that we cannot say that at 
#least 1 u is different for the treatments

#part e
#Ho: u1=u2=u3=u4, Ha: at least 1 u is different
summary(model2B)
#Since 0.0305<0.05, we reject Ho, accept Ha, and can say with a 95% confidence 
#that at least 1 u is different

#part f
TukeyHSD(model2T,"Resort")
#Using the Tukey's Method, it appears that all of the comparisons have a 
#negative on the lower end and a positive on the upper end, which shows that we
#cannot say that one is different from the other (which also lines up with our 
#failure of Ho in part d)

#Question 4
#part a
#The treatments are 10 AM, on the hour; 10 AM, on the half hour;10 AM, early; 
#10 AM, late; 4 pm, hour; 4 pm, half hour; 4 pm, early; 4 pm, late; 9pm, hour; 
#9 pm half hour; 9 pm, early; and 9 pm, late

#part b
response<-c(42, 36, 62, 51, 37, 41, 68, 47, 41, 38, 64, 48, 62, 57, 88, 67, 60, 
            60, 85, 60, 58, 55, 81, 66, 100, 97, 127, 105, 96, 96, 120, 101, 
            103, 101, 126, 107)

Time<-c("10 AM","10 AM","10 AM","10 AM","10 AM","10 AM","10 AM","10 AM","10 AM",
        "10 AM","10 AM","10 AM","4 PM","4 PM","4 PM","4 PM","4 PM","4 PM","4 PM"
        ,"4 PM","4 PM","4 PM","4 PM","4 PM","9 PM","9 PM","9 PM","9 PM","9 PM",
        "9 PM","9 PM","9 PM","9 PM","9 PM","9 PM","9 PM")

Position<-c("On the hour", "On the half hour", "Early", "Late","On the hour", 
            "On the half hour", "Early", "Late","On the hour", 
            "On the half hour", "Early", "Late","On the hour", 
            "On the half hour", "Early", "Late","On the hour", 
            "On the half hour", "Early", "Late","On the hour", 
            "On the half hour", "Early", "Late","On the hour", 
            "On the half hour", "Early", "Late","On the hour", 
            "On the half hour", "Early", "Late","On the hour", 
            "On the half hour", "Early", "Late")


data_input3<-data.frame(Time=factor(Time), Position=factor(Position), response)

ggplot(data_input3, aes(x = Time, y = response, col=Position, group=Position))+ 
 stat_summary(fun=mean, geom="line")


#part c
model3I<-aov(response~Time*Position, data=data_input3)
summary(model3I)

#Since <2e-16 is less than 0.05, we reject Ho and say that there is an 
#interaction between the position and the time

#part d
model3T<-aov(response~Time, data=data_input3)
summary(model3T)

#Since 1.11e-13<0.05, we can also reject Ho and say that at least one of the 
#means of time is different

#part e
model3P<-aov(response~Position, data=data_input3)
summary(model3P)


#Since 0.141>0.05, we fail to reject Ho, and as such we cannot say that at least
#one of the means of position is different

#part f
TukeyHSD(model3P,"Position")
#Looking at the Tukey's Model, we can see that there is no evidence of 
#difference between position, which lines up with our hypothesis test at part e

#part g
TukeyHSD(model3T, "Time")
#Looking at this Tukey's Model, we can see that there is a difference between 
#all possible means. It shows that largest response is 9 PM, then 4 PM and then
#10 AM being last. 

#part h

TukeyHSD(model3I, "Time:Position")
#Looking at the possibilities, the best option is 9 PM, Early, as it have the 
#more responses compared to all of the other options


```
```
